Create macro inferred schema and coinmarketcap staging
Claraval-DataLab/Claraval-DW-Demo pull request #6
Opened 2024-05-15 20:07 UTC by diegogarcia-claravaldatalab

**Added macros and new staging models:** 

- **What has been changed?**
  - Added macros in `macros/get_inferred_schema.sql` and created two new staging models in `models/staging/coinmarketcap/`: `stg_coinmarketcap__map_tokens.sql` and `stg_coinmarketcap__new_tokens.sql`.

- **Why was it changed?**
  - The macros were added to improve the reusability and maintainability of the code, while the new staging models were created to accommodate specific data transformations and mappings related to the CoinMarketCap data.

#### Impact:

- **Which areas of the project are affected?**
  - The changes affect the data transformation process for the CoinMarketCap data and improve the overall architecture of the project by introducing reusable macros.

#### Testing and Linting:

- **How have the changes been tested?**
  - The macros and staging models have been tested by running them against sample data to ensure they produce the expected results.

#### Documentation:

- **Has the documentation been updated?**
  - Yes, the documentation has been updated to include information about the new macros and staging models, their purpose, and how to use them.

#### Merge Checklist:

- [x] The documentation compiles without errors.
- [ ] All tests pass (if applicable). (Please complete this before merging)
- [x] Code has been linted and passes linting checks.
- [x] Documentation has been updated.

#### Screenshots:

No screenshots are applicable as this is a textual update.

#### Additional Comments:

No additional comments.

2024-05-15 20:09 UTC, diegogarcia-claravaldatalab commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +        data AS js_new_tokens_data,
@tuliolima o que acha de chamar um json com prefico js? Será que seria confundido com JavaScript?

2024-05-15 20:19 UTC, diegogarcia-claravaldatalab commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +    SELECT * FROM {{ source('coinmarketcap','map_tokens') }}
@tuliolima aqui o pessoal usava uma macro que inferia e criava uma source unindo o database + tabela e mais os underscores, olhei na documentação do DBT e não tem isso, eles usar o "ref" só para modelos existentes. Não vou aplicar ao projeto para não ficar diferente do padrão e da documentação do DBT.

2024-05-15 21:35 UTC, tuliolima requested changes

2024-05-15 21:35 UTC, tuliolima commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +        data AS js_new_tokens_data,
Eu ainda não entendi o ganho de colocar prefixos nas colunas, é algo bem diferente do que é usado em qualquer lugar e é inconsistente em alguns casos:
- dificulta o entendimento e a legibilidade dos campos, ex: `first_name` -> `nm_first`, o `nm` significa que é o primeiro nome ou que é uma campo de texto que se chama `first`? Se tiver dois campos: `first` e `first_name` eles vão ficar iguais? Se for `first_name` e `surname` vai ficar `nm_first` e `nm_surname`?
- Fica o contrário da leitura em Inglês: lemos `user name` e não `name user`, `airbyte raw id` e não `id airbyte raw`.
- o prefixo não corresponde diretamente ao tipo de dado: `id` não diz exatamente se o campo é textual ou numérico. Se estiver salvando uma string timestamp eu uso `ts` ou `nm`?
- Se for um array, vamos especificar só o prefixo `arr`? os campos `names` e `values` seriam `arr_names` e `arr_values`?
- E definirmos um prefixo que não corresponde ao tipo de dados isso não vai ser checado, ex: usar `js` em um campo string.
- normalmente a forma como definimos os nomes já deixa claro o significado: user_id, user_name, created_at, last_events. Sem contar que o tipo de dados pode ser especificado na documentação do modelo e vai estar na tabela do BigQuery. 


Acha mesmo que vale a pena continuar com essa notação?

2024-05-15 21:35 UTC, tuliolima commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +SELECT * FROM final
Não entendo o motivo de usar esse select final, não vejo ganho de legibilidade do código porque ele está sempre no final, você só lê depois que tudo já foi visto e é igual em todos os modelos. Também não tem utilidade lógica, funcionaria da mesma forma sem. É um boilerplate que podemos cortar e deixar a query mais simples, com menos linhas. O que acha?

2024-05-15 21:35 UTC, tuliolima commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +LIMIT 1
Porque fazer esse limit? Talvez tenha sido esquecido.

2024-05-15 21:35 UTC, tuliolima commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +SELECT * FROM final
Idem para os outros modelos.

2024-05-15 21:35 UTC, tuliolima commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +-- Created at: 2024-05-14
Poderíamos usar o campo de metadados pra definir esse cabeçalho, os dados ficariam salvos no manifest, apareceria no dbt docs e daria pra acessar programaticamente. O que acha?

```python
{{ config(
    meta = {
        'business_goal': 'Get CoinMarketCap map all tokens from https://coinmarketcap.com/pt-br/',
        'creator': 'Diego Garcia',
        'created_at': '2024-05-14'
    }
) }}
```

2024-05-15 21:40 UTC, tuliolima commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +    SELECT * FROM {{ source('coinmarketcap','map_tokens') }}
Diego, lá o pessoal também usa o `source` do mesmo jeito, não sei de qual macro você está falando.

2024-05-15 21:42 UTC, tuliolima commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +-- Created at: 2024-05-14
Daria pra fazer algum check pra garantir que todos os modelos tenham os metadados. Também daria pra usar em algum data catalog.

2024-05-15 21:47 UTC, diegogarcia-claravaldatalab commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +SELECT * FROM final
- A parte da notação, é uma convenção para dar mais agilidade em tabelas com muitas variáveis, pois quando você começa digitando "id..." o auto-complete vai apresentar apenas os campos com o prefixo desejado, além de auxiliar porque quando você está digitando "nm..." já sabe que vem uma string, um "vl..." já sabe que é um float..
- Sobre o select do final, o modelo performa melhor segundo os vídeos de treinamento do DBT Fundamentals, pois teoricamente a query toda está sendo carregada em memória (não sei se para queries maiores ele cria uma tabela temporária). Queria seguir esse padrão para que quando mais pessoas começassem a mexer no projeto, a documentação do DBT bastasse para aprenderem.

2024-05-15 21:50 UTC, diegogarcia-claravaldatalab commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +LIMIT 1
Fix!

2024-05-15 21:51 UTC, diegogarcia-claravaldatalab commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +-- Created at: 2024-05-14
Interessante, não conhecia essa feature.

2024-05-15 21:54 UTC, diegogarcia-claravaldatalab commented on macros/get_inferred_schema.sql
> +    {%- elif 'stg_' in model_name or 'int_' in model_name  -%}
Ajustado.

2024-05-15 22:26 UTC, tuliolima commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +SELECT * FROM final
Não vejo sentido em buscar campos pelo prefixo por que normalmente você não está buscando qualquer campo que seja um `id` ou qualquer campo que seja um `vl` mas algum campo específico pelo nome dele, independente do tipo, ex: se quero usar o cpf então busco `cpf`, independente se começar com `id` ou `nm` ou `cd`.
Mas enfim, não vou insistir com isso, é que não vejo ganho que compense.

2024-05-15 22:27 UTC, tuliolima commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +SELECT * FROM final
Sobre o Select eu não sabia que tivesse algum impacto na performance, é estranho mas vou pesquisar mais sobre isso.

2024-05-16 12:18 UTC, diegogarcia-claravaldatalab commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +    SELECT * FROM {{ source('coinmarketcap','map_tokens') }}
Tem uma macro que eles usavam para forçar pegar a source, mesmo que não materializada nos modelos mais atuais. Porque confundia os novos do porque usar o "source" quando é staging e usar o "ref" quando eram tabelas materializadas em view ou table. Mas acho que não tem problema, está assim na própria documentação do DBT.

2024-05-16 19:16 UTC, diegogarcia-claravaldatalab commented on models/staging/coinmarketcap/stg_coinmarketcap__map_tokens.sql
> +-- Created at: 2024-05-14
Ajustado.

2024-05-16 19:22 UTC, diegogarcia-claravaldatalab commented on macros/get_inferred_schema.sql
> +    {%- if 'dim_' in model_name -%}
Ajustado.

2024-05-16 19:23 UTC, diegogarcia-claravaldatalab commented on dbt_project.yml
> +  DBT_TIME_ZONE: "America/Sao_Paulo"
Somente deixei a conversão para `DATETIME` . Só não pode esquecer de converter no datamart.

2024-05-16 19:24 UTC, merged